spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST_PORT:localhost:5432}/coffer
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    change-log: changelog.xml
    default-schema: public
    drop-first: false
    enabled: true
jwt:
  secret: dgdgsgdgdhdgdgsgdgdhdgdgsgdgdhdgdgsgdgdhdgdgsgdgdh
logging:
  level:
    org.springframework.security: TRACE

